// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paqueteria.Models;

namespace Paqueteria.Migrations
{
    [DbContext(typeof(PaqueteriaContext))]
    [Migration("20181105212319_Primera")]
    partial class Primera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Paqueteria.Models.Aplicacion", b =>
                {
                    b.Property<int>("AplicacionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionApp")
                        .HasMaxLength(100);

                    b.Property<string>("DetalleApp")
                        .HasMaxLength(100);

                    b.Property<int>("EstatusID");

                    b.Property<DateTime>("FinalDate");

                    b.Property<string>("NombreApp")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("StartDate");

                    b.HasKey("AplicacionID");

                    b.HasIndex("EstatusID");

                    b.ToTable("Aplicacion");
                });

            modelBuilder.Entity("Paqueteria.Models.AplicacionPaquete", b =>
                {
                    b.Property<int>("AplicacionID");

                    b.Property<int>("PaqueteID");

                    b.HasKey("AplicacionID", "PaqueteID");

                    b.HasIndex("PaqueteID");

                    b.ToTable("AplicacionPaquete");
                });

            modelBuilder.Entity("Paqueteria.Models.Dependencia", b =>
                {
                    b.Property<int>("DependenciaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionDpd")
                        .HasMaxLength(100);

                    b.Property<int>("EstatusID");

                    b.Property<DateTime>("FinaltDate");

                    b.Property<string>("NombreDpd")
                        .IsRequired();

                    b.Property<DateTime>("StartDate");

                    b.HasKey("DependenciaID");

                    b.ToTable("Dependencia");
                });

            modelBuilder.Entity("Paqueteria.Models.Estatus", b =>
                {
                    b.Property<int>("EstatusID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionSts");

                    b.Property<string>("NombreSts");

                    b.HasKey("EstatusID");

                    b.ToTable("Estatus");
                });

            modelBuilder.Entity("Paqueteria.Models.Incidencia", b =>
                {
                    b.Property<int>("IncidenciaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionIc")
                        .IsRequired();

                    b.Property<int>("EstatusID");

                    b.Property<DateTime>("FinaltDate");

                    b.Property<string>("NombreIc")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("PaqueteID");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("IncidenciaID");

                    b.HasIndex("PaqueteID");

                    b.ToTable("Incidecia");
                });

            modelBuilder.Entity("Paqueteria.Models.Paquete", b =>
                {
                    b.Property<int>("PaqueteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DescripcionPck")
                        .HasMaxLength(100);

                    b.Property<string>("DetallePck")
                        .HasMaxLength(100);

                    b.Property<int>("EstatusID");

                    b.Property<DateTime>("FinalDate");

                    b.Property<string>("NombrePck")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("StartDate");

                    b.HasKey("PaqueteID");

                    b.ToTable("Paquete");
                });

            modelBuilder.Entity("Paqueteria.Models.Relacion", b =>
                {
                    b.Property<int>("PaqueteID");

                    b.Property<int>("DependenciaID");

                    b.HasKey("PaqueteID", "DependenciaID");

                    b.HasIndex("DependenciaID");

                    b.ToTable("Relacion");
                });

            modelBuilder.Entity("Paqueteria.Models.Aplicacion", b =>
                {
                    b.HasOne("Paqueteria.Models.Estatus")
                        .WithMany("Aplicaciones")
                        .HasForeignKey("EstatusID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Paqueteria.Models.AplicacionPaquete", b =>
                {
                    b.HasOne("Paqueteria.Models.Aplicacion", "Aplicacion")
                        .WithMany()
                        .HasForeignKey("AplicacionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Paqueteria.Models.Paquete", "Paquete")
                        .WithMany("AplicacionPaquetes")
                        .HasForeignKey("PaqueteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Paqueteria.Models.Incidencia", b =>
                {
                    b.HasOne("Paqueteria.Models.Paquete", "Paquete")
                        .WithMany("Incidencias")
                        .HasForeignKey("PaqueteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Paqueteria.Models.Relacion", b =>
                {
                    b.HasOne("Paqueteria.Models.Dependencia", "Dependencia")
                        .WithMany("Relacions")
                        .HasForeignKey("DependenciaID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Paqueteria.Models.Paquete", "Paquete")
                        .WithMany("Relacions")
                        .HasForeignKey("PaqueteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
